/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibrary;

/**
 *
 * @author Software-19
 */
public class FormDataFixed extends javax.swing.JFrame {

    /**
     * Creates new form FormMemberData
     */
    public FormDataFixed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        var_female = new javax.swing.JRadioButton();
        var_male = new javax.swing.JRadioButton();
        cmb_kelas = new javax.swing.JComboBox<>();
        cmb_kompetensi = new javax.swing.JComboBox<>();
        btn_lihat_data = new javax.swing.JButton();
        btn_edit1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(167, 198, 249));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Data Anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 70));

        txt_nama.setForeground(new java.awt.Color(102, 102, 102));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txt_nis.setForeground(new java.awt.Color(102, 102, 102));
        txt_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nisActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btn_submit.setBackground(new java.awt.Color(58, 156, 253));
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Simpan");
        btn_submit.setAutoscrolls(true);
        btn_submit.setBorderPainted(false);
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, 30));

        btn_back.setBackground(new java.awt.Color(153, 153, 153));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Kembali");
        btn_back.setAutoscrolls(true);
        btn_back.setBorderPainted(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kompetensi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 240, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        buttonGroup1.add(var_female);
        var_female.setText("Perempuan");
        jPanel1.add(var_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        buttonGroup1.add(var_male);
        var_male.setText("Laki-laki");
        var_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_maleActionPerformed(evt);
            }
        });
        jPanel1.add(var_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        cmb_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kelas --", "X", "Sebelas", "12" }));
        cmb_kelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kelasItemStateChanged(evt);
            }
        });
        cmb_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_kelasMouseClicked(evt);
            }
        });
        cmb_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kelasActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, -1));

        cmb_kompetensi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kompetensi --", "Rekayasa Perangkat Lunak", "Desain Komunikasi Visual", "Teknik Komputer Jaringan" }));
        jPanel1.add(cmb_kompetensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 240, -1));

        btn_lihat_data.setBackground(new java.awt.Color(255, 204, 0));
        btn_lihat_data.setForeground(new java.awt.Color(255, 255, 255));
        btn_lihat_data.setText("Lihat Data");
        btn_lihat_data.setAutoscrolls(true);
        btn_lihat_data.setBorderPainted(false);
        btn_lihat_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lihat_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihat_dataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lihat_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 90, 30));

        btn_edit1.setBackground(new java.awt.Color(255, 204, 0));
        btn_edit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit1.setText("Edit");
        btn_edit1.setAutoscrolls(true);
        btn_edit1.setBorderPainted(false);
        btn_edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit1ActionPerformed

    private void btn_lihat_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihat_dataActionPerformed
        // TODO add your handling code here:
        DataAnggota dataAnggota = new DataAnggota();
        dataAnggota.setVisible(true);
        dataAnggota.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_lihat_dataActionPerformed

    private void cmb_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasActionPerformed

    private void cmb_kelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_kelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasMouseClicked

    private void cmb_kelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kelasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasItemStateChanged

    private void var_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_maleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_var_maleActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        clear();

    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        String nama;
        String nis;
        String kelas;
        String kompetensi;
        String jk;
        String alamat;

        nama = txt_nama.getText();
        nis = txt_nis.getText();
        kelas = cmb_kelas.getSelectedItem().toString();
        kompetensi = cmb_kompetensi.getSelectedItem().toString();
        alamat = txt_alamat.getText();

        if(var_male.isSelected()){
            jk = "L";
        }else{
            jk = "P";
        }

        txt_nama.setText("");
        txt_nis.setText("");
        cmb_kelas.setSelectedItem(0);
        cmb_kompetensi.setSelectedItem(0);
        txt_alamat.setText("");
        buttonGroup1.clearSelection();

        txt_nama.requestFocus();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nisActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void clear(){
        txt_nama.setText("");
        txt_nis.setText("");
        cmb_kelas.setSelectedItem(0);
        cmb_kompetensi.setSelectedItem(0);
        txt_alamat.setText("");
        buttonGroup1.clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataFixed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormDataFixed().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_edit1;
    private javax.swing.JButton btn_lihat_data;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb_kelas;
    private javax.swing.JComboBox<String> cmb_kompetensi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JRadioButton var_female;
    private javax.swing.JRadioButton var_male;
    // End of variables declaration//GEN-END:variables
}
