/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibrary;

/**
 *
 * @author Software-19
 */
public class FormPeminjamanBuku extends javax.swing.JFrame {

    /**
     * Creates new form FormMemberData
     */
    public FormPeminjamanBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_penerbit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_lihat_data = new javax.swing.JButton();
        txt_penulis = new javax.swing.JTextField();
        txt_thn1 = new javax.swing.JTextField();
        cmb_kategori = new javax.swing.JComboBox<>();
        btn_edit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(167, 198, 249));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        txt_kode.setForeground(new java.awt.Color(102, 102, 102));
        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Kode Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txt_judul.setForeground(new java.awt.Color(102, 102, 102));
        txt_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_judulActionPerformed(evt);
            }
        });
        jPanel1.add(txt_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Judul Buku");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Penulis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btn_submit.setBackground(new java.awt.Color(58, 156, 253));
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Simpan");
        btn_submit.setAutoscrolls(true);
        btn_submit.setBorderPainted(false);
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 30));

        btn_back.setBackground(new java.awt.Color(153, 153, 153));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Close");
        btn_back.setAutoscrolls(true);
        btn_back.setBorderPainted(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Penerbit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kategori");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 80, -1));
        jPanel1.add(txt_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 260, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tahun Penerbit");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, -1));

        btn_lihat_data.setBackground(new java.awt.Color(255, 204, 0));
        btn_lihat_data.setForeground(new java.awt.Color(255, 255, 255));
        btn_lihat_data.setText("Lihat Data");
        btn_lihat_data.setAutoscrolls(true);
        btn_lihat_data.setBorderPainted(false);
        btn_lihat_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lihat_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihat_dataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lihat_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 90, 30));
        jPanel1.add(txt_penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 250, -1));
        jPanel1.add(txt_thn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 260, -1));

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih kategori Buku --", "Pendidikan", "Komik", "Novel", "Pertanian", "Pemrograman", "Ekonomi", "Sejarah" }));
        jPanel1.add(cmb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 260, -1));

        btn_edit1.setBackground(new java.awt.Color(255, 204, 0));
        btn_edit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit1.setText("Edit");
        btn_edit1.setAutoscrolls(true);
        btn_edit1.setBorderPainted(false);
        btn_edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeActionPerformed

    private void txt_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_judulActionPerformed

    private void clear(){
        txt_kode.setText("");
        txt_judul.setText("");
        txt_penulis.setText("");
        cmb_kategori.getSelectedItem().toString();
        txt_thn1.setText("");
        txt_penerbit.setText("");
        buttonGroup1.clearSelection();
        
    }
    
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        String kode;
        String judul;
        String penulis;
        String penerbit;
        String tahun;
        String kategori;
        
        kode = txt_kode.getText();
        judul = txt_judul.getText();
        penulis = txt_penulis.getText();
        penerbit = txt_penerbit.getText();
        tahun = txt_thn1.getText();
        kategori = cmb_kategori.getSelectedItem().toString();
        
        txt_kode.setText("");
        txt_judul.setText("");
        txt_penulis.setText("");
        txt_penerbit.setText("");
        txt_thn1.setText("");
        cmb_kategori.setSelectedItem(0);
        buttonGroup1.clearSelection();
        
        txt_kode.requestFocus();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        clear();
        
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_lihat_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihat_dataActionPerformed
        // TODO add your handling code here:
        DataBuku dataBuku = new DataBuku();
        dataBuku.setVisible(true);
        dataBuku.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_lihat_dataActionPerformed

    private void btn_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormPeminjamanBuku().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_edit1;
    private javax.swing.JButton btn_lihat_data;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_penulis;
    private javax.swing.JTextField txt_thn1;
    // End of variables declaration//GEN-END:variables
}
