/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibrary;

import javax.swing.JOptionPane;

/**
 *
 * @author Iras Alizubeer
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.pack();  
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        beranda = new javax.swing.JMenu();
        form_data = new javax.swing.JMenu();
        form_anggota_dash = new javax.swing.JMenuItem();
        form_peminjaman_buku = new javax.swing.JMenuItem();
        form_user = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        data_anggota = new javax.swing.JMenuItem();
        data_buku = new javax.swing.JMenuItem();
        data_user = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        profil_perpustakaan = new javax.swing.JMenuItem();
        cari_buku = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(167, 198, 249));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat datang di");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MY LIBRARY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bersama Skinfa wujudkan Indonesia emas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Jelajahi Buku");
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/img/Your paragraph text (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 250, 250));

        beranda.setText("Beranda");
        beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaActionPerformed(evt);
            }
        });
        beranda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                berandaPropertyChange(evt);
            }
        });
        jMenuBar1.add(beranda);

        form_data.setText("Form");
        form_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_dataActionPerformed(evt);
            }
        });

        form_anggota_dash.setText("Form Anggota");
        form_anggota_dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_anggota_dashActionPerformed(evt);
            }
        });
        form_data.add(form_anggota_dash);

        form_peminjaman_buku.setText("Form Buku");
        form_peminjaman_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_peminjaman_bukuActionPerformed(evt);
            }
        });
        form_data.add(form_peminjaman_buku);

        form_user.setText("Form User");
        form_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_userActionPerformed(evt);
            }
        });
        form_data.add(form_user);

        jMenuBar1.add(form_data);

        jMenu1.setText("Data");

        data_anggota.setText("Data Anggota");
        data_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_anggotaActionPerformed(evt);
            }
        });
        jMenu1.add(data_anggota);

        data_buku.setText("Data Buku");
        data_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_bukuActionPerformed(evt);
            }
        });
        jMenu1.add(data_buku);

        data_user.setText("Data User");
        data_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_userActionPerformed(evt);
            }
        });
        jMenu1.add(data_user);

        jMenuBar1.add(jMenu1);

        about.setText("Tentang Kami");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        profil_perpustakaan.setText("Profil Perpustakaan");
        about.add(profil_perpustakaan);

        cari_buku.setText("Cari Buku");
        about.add(cari_buku);

        jMenuBar1.add(about);

        exit.setText("Keluar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_berandaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_berandaPropertyChange

    private void berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berandaActionPerformed

    private void form_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_dataActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Yakin mau keluar?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void form_anggota_dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_anggota_dashActionPerformed
        // TODO add your handling code here:
        FormAnggota formAnggota = new FormAnggota();
        formAnggota.setVisible(true);
        formAnggota.setLocationRelativeTo(null);
    }//GEN-LAST:event_form_anggota_dashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void form_peminjaman_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_peminjaman_bukuActionPerformed
        // TODO add your handling code here:
        FormPeminjamanBuku formBuku = new FormPeminjamanBuku();
        formBuku.setVisible(true);
        formBuku.setLocationRelativeTo(null);
    }//GEN-LAST:event_form_peminjaman_bukuActionPerformed

    private void data_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_anggotaActionPerformed
        // TODO add your handling code here:
        DataAnggota dataAnggota = new DataAnggota();
        dataAnggota.setVisible(true);
        dataAnggota.setLocationRelativeTo(null);
    }//GEN-LAST:event_data_anggotaActionPerformed

    private void form_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_userActionPerformed
        // TODO add your handling code here:
        FormUser formUser = new FormUser();
        formUser.setVisible(true);
        formUser.setLocationRelativeTo(null);
    }//GEN-LAST:event_form_userActionPerformed

    private void data_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_bukuActionPerformed
        // TODO add your handling code here:
        DataBuku dataBuku = new DataBuku();
        dataBuku.setVisible(true);
        dataBuku.setLocationRelativeTo(null);
    }//GEN-LAST:event_data_bukuActionPerformed

    private void data_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_userActionPerformed
        // TODO add your handling code here:
        DataUser dataUser = new DataUser();
        dataUser.setVisible(true);
        dataUser.setLocationRelativeTo(null);
    }//GEN-LAST:event_data_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenu beranda;
    private javax.swing.JMenuItem cari_buku;
    private javax.swing.JMenuItem data_anggota;
    private javax.swing.JMenuItem data_buku;
    private javax.swing.JMenuItem data_user;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuItem form_anggota_dash;
    private javax.swing.JMenu form_data;
    private javax.swing.JMenuItem form_peminjaman_buku;
    private javax.swing.JMenuItem form_user;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem profil_perpustakaan;
    // End of variables declaration//GEN-END:variables

    private Object login() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}