/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mylibrary;

import javax.swing.JOptionPane;

/**
 *
 * @author Iras Alizubeer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.pack();  
        this.setLocationRelativeTo(null);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login_title = new javax.swing.JLabel();
        user_label = new javax.swing.JLabel();
        jt_user = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        jt_password = new javax.swing.JPasswordField();
        b_close = new javax.swing.JButton();
        b_login = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        show_pw = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login_title.setText("Login My Library");
        jPanel1.add(Login_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 20, -1, -1));

        user_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user_label.setText("Username");
        jPanel1.add(user_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        jPanel1.add(jt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 105, 220, 30));

        password_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_label.setText("Password");
        jPanel1.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));
        jPanel1.add(jt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 175, 220, 30));

        b_close.setForeground(new java.awt.Color(167, 198, 249));
        b_close.setText("Close");
        jPanel1.add(b_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 70, 20));

        b_login.setBackground(new java.awt.Color(167, 198, 249));
        b_login.setForeground(new java.awt.Color(255, 255, 255));
        b_login.setText("Login");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });
        jPanel1.add(b_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 70, 20));

        jPanel2.setBackground(new java.awt.Color(167, 198, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/img/logo.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 30, -1, -1));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("My Library");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 160, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 300));

        show_pw.setText("Show");
        show_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pwActionPerformed(evt);
            }
        });
        jPanel1.add(show_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // TODO add your handling code here:
        if (jt_user.getText() .equals("")){
            JOptionPane.showMessageDialog(null, "Mohon isi Username terlebih dahulu");
        } else if(jt_password.getText() .equals("")){
            JOptionPane.showMessageDialog(null, "Mohon isi Password terlebih dahulu");
        } else if(jt_user.getText() .contains("irbadh") && jt_password.getText() .contains("12345")){
            JOptionPane.showMessageDialog(null, "Login Berhasil");
            
            // Buka halaman Home
            Home home = new Home();  // panggil JFrame lain
            home.setVisible(true);
            
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "Password atau Username salah!", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_loginActionPerformed

    private void show_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pwActionPerformed
        // TODO add your handling code here:
        if(show_pw .isSelected()){
        jt_password.setEchoChar((char)0);
        } else{
        jt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_show_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_title;
    private javax.swing.JButton b_close;
    private javax.swing.JButton b_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jt_password;
    private javax.swing.JTextField jt_user;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password_label;
    private javax.swing.JCheckBox show_pw;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
